version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

# x64 is a CMake-compatible solution platform name.
# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - x64

# Build Configurations, i.e. Debug, Release, etc.
configuration:
- Debug
- Release

# Environment variables: add Python3 path and only on Debug also
# EXCLUDETESTS to exclude tests which would take too much time
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      EXCLUDETESTS: solver
    - PYTHON: "C:\\Python36-x64"
      EXCLUDETESTS:
matrix:
  exclude:
    - configuration: Release
      EXCLUDETESTS: solver
    - configuration: Debug
      EXCLUDETESTS:
        
# Cmake will autodetect the compiler, but we set the arch
before_build:
  - set PATH=%PYTHON%;%PATH%
  - set CXXFLAGS=%additional_flags%
  - cmake -H. -BBuild -A%PLATFORM% -DUI_CXX_USE_QT=OFF

# Build with MSBuild
build:
  project: Build\spirit.sln # path to Visual Studio solution or project
  parallel: true                 # enable MSBuild parallel builds
  verbosity: normal              # MSBuild verbosity level {quiet|minimal|normal|detailed}

install:
  - "%PYTHON%/Scripts/pip.exe install numpy"

test_script:
  - cd Build
  - ctest --output-on-failure -C %CONFIGURATION% -E %EXCLUDETESTS%