sudo: required
dist: trusty
language: cpp


cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0


matrix:
  include:
    # Linux, GCC 5.1
    - os: linux
      env: COMPILER_C=gcc-5 COMPILER_CXX=g++-5 USE_CUDA="false" CMAKE_OPTIONS="-DUSER_PATH_QT=~/opt/qt57"
      compiler: g++
      addons:
        apt:
          packages:
          - g++-5
          - qt57base
          - qt57charts-no-lgpl
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:beineri/opt-qt571-trusty'
    # Linux, GCC 6
    - os: linux
      env: COMPILER_C=gcc-6 COMPILER_CXX=g++-6 USE_CUDA="false" CMAKE_OPTIONS="-DUSER_PATH_QT=~/opt/qt57"
      compiler: g++
      addons:
        apt:
          packages:
          - g++-6
          - qt57base
          - qt57charts-no-lgpl
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:beineri/opt-qt571-trusty'
    # OSX, xcode 8
    - os: osx
      osx_image: xcode8
      env: USE_CUDA="false" CMAKE_OPTIONS="-DUSER_PATH_QT=~/usr/local/Cellar/qt@5.7/5.7.1"

    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.6
    #       packages:
    #         - clang-3.6
    #   env: COMPILER=clang++-3.6
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.7
    #       packages:
    #         - clang-3.7
    #   env: COMPILER=clang++-3.7


before_install:
    - sudo pip install numpy
    - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'


install:
  # Setup default versions and override compiler if needed
  - if [[ "${LLVM_VERSION}" == "default" ]]; then LLVM_VERSION=3.9.0; fi
  # Install a recent CMake (unless already installed on OS X)
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
      mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      export CC=${COMPILER_C} CXX=${COMPILER_CXX}
      source /opt/qt57/bin/qt57-env.sh
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      brew install cppcheck qt@5.7
      brew link --force qt@5.7
      export PATH=/usr/local/opt/qt@5.7/bin:${PATH}
    fi
#   # Install CUDA
#   - |
#     if [[ "${USE_CUDA}" == "true" ]]; then
#       echo "Installing CUDA"
#       wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb
#       sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb
#     fi
#   - |
#     if [[ "${USE_CUDA}" == "true" ]]; then
#       cd ${TRAVIS_BUILD_DIR}
#       sudo apt-get update
#       sudo apt-get install cuda-drivers cuda-core-7-0 cuda-cudart-dev-7-0
#       CMAKE_OPTIONS+="  -DUSE_CUDA=OFF -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda"
#     fi


script:
  - cd ${TRAVIS_BUILD_DIR}
  - |
    mkdir -p build
    cd build
    cmake ${CMAKE_OPTIONS} ..
    cd ..
  - ./make.sh -j8
  - ./ctest.sh